module.exports = {
  // Action types
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  REMOVE_POST: 'REMOVE_POST',

  CREATING_COMMENT: 'CREATE_COMMENT',
  CREATING_COMMENT_DONE: 'CREATING_COMMENT_DONE',
  CREATING_COMMENT_FAILED: 'CREATING_COMMENT_FAILED',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',

  UPDATE_PROFILE: 'UPDATE_PROFILE',

};