module.exports = {
  // Action types
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  REMOVE_POST: 'REMOVE_POST',

  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',

  UPDATE_PROFILE: 'UPDATE_PROFILE',

};